### ISSUE TITLE
INTERFACE_PARAMETERS definition is missing in alphatims.utils (standalone installer 0.2.4)

### ISSUE THREAD

**Issue by caetera** [MannLabs/alphatims#114]
**Describe the bug**
Alphatims fails to start with the error `AttributeError: module 'alphatims.utils' has no attribute 'INTERFACE_PARAMETERS'`

**To Reproduce**
1. Install v 0.2.4 through GUI installer on windows
2. Start the software

**Logs**

Traceback (most recent call last):
  File "alphatims_pyinstaller.py", line 4, in <module>
AttributeError: module 'alphatims.utils' has no attribute 'INTERFACE_PARAMETERS'
[15952] Failed to execute script alphatims_pyinstaller

**Version (please complete the following information):**
 - Installation Type One-Click Installer
 - If no log is available, provide the following:
   - Platform information
     - system    Windows
     - release   20H2
     - version   10.0.19042.928
     - machine   x86_64
   - Python information:
     - alphatims version 0.2.4

**Comment by swillems** [comment]
Thank you for reporting this.
This should be fixed in the latest release (0.2.5), which is now available on the GitHub main branch and PyPi.

Extra info:
* This issue was an artefact of not updating the pyinstaller script after refactoring source code.
* Release 0.2.4 on GitHub has been marked as a "pre-release" to disencourage more downloads while keeping it available for transparancy and reproducibility purposes.
* The Python code itself was unaffected. The Pypi release therefore remains available as this should be fully functional.
